import { StyleSheet } from "react-native";

import { colors, radii, sizes, spacing, typography } from "@/theme/tokens";

export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: colors.background },
  darkScreen: { backgroundColor: colors.darkBackground },
  darkText: { color: colors.darkText },
  darkInput: {
    color: colors.darkText,
    backgroundColor: colors.darkSurface,
    borderColor: "#4A4E47",
  },
  darkHeader: { backgroundColor: colors.darkBackground, borderBottomColor: colors.darkBorder },
  loadingScreen: { alignItems: "center", justifyContent: "center" },
  centered: { alignItems: "center", justifyContent: "center", paddingHorizontal: spacing.large },
  header: {
    minHeight: 70,
    paddingHorizontal: spacing.medium,
    paddingTop: spacing.medium,
    paddingBottom: spacing.large,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  headerTitle: { color: colors.textStrong, fontSize: 17, fontWeight: typography.extraBold },
  headerSide: { width: sizes.medium },
  backHitbox: {
    width: 36,
    height: sizes.medium,
    alignItems: "flex-start",
    justifyContent: "center",
  },
  backButton: { width: sizes.medium, height: sizes.medium, justifyContent: "center" },
  backIcon: {
    color: colors.textStrong,
    fontSize: 38,
    lineHeight: 38,
    fontWeight: typography.light,
  },
  cancel: { color: colors.textMuted, fontSize: typography.body },
  save: { color: colors.primary, fontSize: typography.body, fontWeight: typography.extraBold },
  content: { paddingHorizontal: spacing.large, paddingTop: spacing.extraLarge },
  eyebrow: { color: colors.primary, fontSize: 12, fontWeight: typography.bold, letterSpacing: 1.8 },
  title: {
    color: colors.textStrong,
    fontSize: typography.title,
    lineHeight: 36,
    fontWeight: typography.extraBold,
    marginTop: spacing.small,
  },
  subtitle: {
    color: colors.textMuted,
    fontSize: typography.body,
    lineHeight: 22,
    marginTop: spacing.small,
  },
  intro: {
    color: colors.textMuted,
    fontSize: typography.body,
    textAlign: "center",
    marginTop: spacing.small,
  },
  profileAvatar: {
    width: sizes.large,
    height: sizes.large,
    borderRadius: radii.round,
    backgroundColor: colors.textStrong,
    alignItems: "center",
    justifyContent: "center",
  },
  profileInitial: { color: colors.background, fontSize: 16, fontWeight: typography.extraBold },
  newChatButton: {
    position: "absolute",
    right: spacing.large,
    width: sizes.large,
    height: sizes.large,
    borderRadius: radii.large,
    backgroundColor: colors.primary,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: colors.textStrong,
    shadowOpacity: 0.16,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 5 },
    elevation: 5,
  },
  newChatIcon: { color: colors.white, fontSize: 28, fontWeight: typography.light, lineHeight: 30 },
  searchWrap: {
    marginHorizontal: spacing.medium,
    height: 50,
    borderRadius: 14,
    backgroundColor: colors.surfaceMuted,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: spacing.medium,
  },
  darkSearchWrap: { backgroundColor: colors.darkSurface },
  searchIcon: {
    color: colors.textMuted,
    fontSize: 26,
    lineHeight: 26,
    marginRight: spacing.small,
    transform: [{ rotate: "-20deg" }],
  },
  searchInput: { flex: 1, color: colors.textStrong, fontSize: typography.body, paddingVertical: 0 },
  clearSearch: {
    color: colors.textMuted,
    fontSize: 23,
    lineHeight: 24,
    paddingLeft: spacing.small,
  },
  listHeader: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: spacing.large,
    paddingTop: spacing.extraLarge,
    paddingBottom: spacing.small,
  },
  sectionTitle: { color: colors.textStrong, fontSize: 17, fontWeight: typography.extraBold },
  count: {
    color: colors.textFaint,
    fontSize: 13,
    fontWeight: typography.bold,
    marginLeft: spacing.small,
  },
  listErrorText: {
    color: colors.danger,
    fontSize: 13,
    marginHorizontal: spacing.large,
    marginBottom: spacing.small,
  },
  listContent: { paddingHorizontal: spacing.medium },
  conversation: {
    minHeight: 82,
    paddingHorizontal: spacing.small,
    paddingVertical: 12,
    flexDirection: "row",
    alignItems: "center",
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.border,
  },
  conversationPressed: { opacity: 0.65 },
  avatar: {
    width: 54,
    height: 54,
    borderRadius: 50,
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
  },
  avatarText: { color: colors.white, fontSize: 15, fontWeight: typography.extraBold },
  onlineDot: {
    position: "absolute",
    width: sizes.extraSmall,
    height: sizes.extraSmall,
    borderRadius: radii.round,
    backgroundColor: colors.success,
    borderWidth: 2,
    borderColor: colors.background,
    right: 5,
    bottom: 0,
  },
  conversationBody: { flex: 1, marginLeft: 14, minWidth: 0 },
  rowBetween: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  name: { color: colors.text, fontSize: 16, fontWeight: typography.bold, flexShrink: 1 },
  unreadName: { color: colors.textStrong, fontWeight: typography.extraBold },
  timestamp: { color: colors.textFaint, fontSize: typography.caption, marginLeft: spacing.small },
  unreadTimestamp: { color: colors.primary, fontWeight: typography.bold },
  preview: {
    color: colors.textMuted,
    fontSize: 14,
    marginTop: 7,
    paddingRight: spacing.small,
    flex: 1,
  },
  unreadPreview: { color: colors.text, fontWeight: typography.semibold },
  unreadBadge: {
    minWidth: 22,
    height: 22,
    borderRadius: radii.round,
    backgroundColor: colors.primary,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: spacing.small,
    marginLeft: spacing.small,
  },
  unreadText: {
    color: colors.white,
    fontSize: typography.caption,
    fontWeight: typography.extraBold,
  },
  stateBox: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: spacing.extraLarge,
  },
  stateText: {
    color: colors.textMuted,
    fontSize: 14,
    textAlign: "center",
    marginTop: spacing.small,
  },
  emptyTitle: {
    color: colors.text,
    fontSize: 18,
    fontWeight: typography.extraBold,
    textAlign: "center",
  },
  avatarButton: {
    alignSelf: "center",
    width: sizes.extraLarge,
    height: sizes.extraLarge,
    position: "relative",
  },
  avatarFallback: {
    width: sizes.extraLarge,
    height: sizes.extraLarge,
    borderRadius: 100,
    backgroundColor: colors.textStrong,
    alignItems: "center",
    justifyContent: "center",
  },
  avatarImage: { width: sizes.extraLarge, height: sizes.extraLarge, borderRadius: 100 },
  avatarInitials: { color: colors.background, fontSize: 30, fontWeight: typography.extraBold },
  cameraBadge: {
    position: "absolute",
    bottom: 0,
    right: 0,
    width: 34,
    height: 34,
    borderRadius: radii.round,
    backgroundColor: colors.primary,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 3,
    borderColor: colors.background,
  },
  cameraIcon: { color: colors.white, fontSize: 24, lineHeight: 25, fontWeight: typography.light },
  changePhoto: {
    color: colors.primary,
    fontSize: 14,
    fontWeight: typography.bold,
    textAlign: "center",
    marginTop: spacing.medium,
  },
  fieldGroup: { marginTop: 54 },
  label: {
    color: colors.textMuted,
    fontSize: typography.label,
    fontWeight: typography.extraBold,
    letterSpacing: 1.4,
    marginBottom: spacing.small,
  },
  inputWrap: {
    height: 54,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: colors.borderInput,
    backgroundColor: colors.surface,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: spacing.medium,
  },
  inputError: { borderColor: colors.danger },
  atSign: {
    color: colors.textFaint,
    fontSize: 18,
    fontWeight: typography.bold,
    marginRight: spacing.small,
  },
  input: { color: colors.textStrong, fontSize: 16, flex: 1, paddingVertical: 0 },
  helper: { color: colors.textFaint, fontSize: 13, marginTop: spacing.small },
  errorText: { color: colors.danger, fontSize: 13, marginTop: spacing.small },
  settingsSection: { marginTop: spacing.extraLarge },
  settingRow: {
    minHeight: 72,
    paddingHorizontal: 14,
    borderRadius: 14,
    backgroundColor: colors.surface,
    flexDirection: "row",
    alignItems: "center",
    marginTop: spacing.small,
  },
  darkSettingRow: { backgroundColor: colors.darkSurface },
  settingCopy: { flex: 1 },
  settingTitle: { color: colors.textStrong, fontSize: 15, fontWeight: typography.extraBold },
  settingSubtitle: {
    color: colors.textFaint,
    fontSize: typography.caption,
    marginTop: spacing.extraSmall,
  },
  modeToggle: {
    flexDirection: "row",
    borderRadius: radii.small,
    backgroundColor: colors.surfaceMuted,
    padding: spacing.extraSmall,
  },
  modeOption: { minWidth: 48, paddingVertical: 7, borderRadius: radii.small, alignItems: "center" },
  activeModeOption: { backgroundColor: colors.primary },
  modeText: { color: colors.textMuted, fontSize: typography.caption, fontWeight: typography.bold },
  activeModeText: { color: colors.white },
  messageList: { paddingHorizontal: 18, paddingTop: spacing.large, paddingBottom: 18 },
  emptyList: { flexGrow: 1, alignItems: "center", justifyContent: "center" },
  headerInfo: { flex: 1, marginLeft: 12 },
  status: { color: colors.success, fontSize: typography.caption, marginTop: spacing.extraSmall },
  moreButton: { width: 36, alignItems: "flex-end" },
  moreText: { color: colors.textMuted, fontSize: 17, letterSpacing: 2 },
  messageRow: { alignSelf: "flex-start", maxWidth: "82%", marginBottom: 14 },
  myMessageRow: { alignSelf: "flex-end", alignItems: "flex-end" },
  groupedMessage: { marginTop: -7 },
  senderLabel: {
    color: colors.textFaint,
    fontSize: typography.label,
    marginBottom: spacing.extraSmall,
    marginLeft: spacing.extraSmall,
  },
  bubble: { borderRadius: 18, paddingHorizontal: 15, paddingVertical: 11 },
  theirBubble: { backgroundColor: colors.surfaceMuted, borderBottomLeftRadius: 5 },
  myBubble: { backgroundColor: colors.primary, borderBottomRightRadius: 5 },
  messageText: { color: colors.text, fontSize: typography.body, lineHeight: 21 },
  myMessageText: { color: colors.white },
  messageMeta: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: spacing.extraSmall,
    gap: spacing.extraSmall,
  },
  time: { color: colors.textFaint, fontSize: 10 },
  delivery: { color: colors.textFaint, fontSize: 10 },
  composerWrap: {
    paddingHorizontal: spacing.medium,
    paddingTop: spacing.small,
    flexDirection: "row",
    alignItems: "flex-end",
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: colors.border,
    backgroundColor: colors.background,
  },
  composer: {
    flex: 1,
    maxHeight: 110,
    minHeight: 46,
    borderRadius: 18,
    backgroundColor: colors.surfaceMuted,
    color: colors.textStrong,
    fontSize: typography.body,
    paddingHorizontal: spacing.medium,
    paddingTop: 13,
    paddingBottom: 11,
  },
  darkComposer: { backgroundColor: colors.darkSurface, color: colors.darkText },
  sendButton: {
    width: 46,
    height: 46,
    borderRadius: radii.round,
    backgroundColor: colors.primary,
    alignItems: "center",
    justifyContent: "center",
    marginLeft: spacing.small,
  },
  sendButtonDisabled: { backgroundColor: "#CBD5E1" },
  sendIcon: { color: colors.white, fontSize: 25, lineHeight: 27, fontWeight: typography.bold },
  missingTitle: { color: colors.text, fontSize: 18, fontWeight: typography.extraBold },
  backButtonText: { color: colors.white, fontWeight: typography.bold },
  noResult: {
    marginTop: spacing.large,
    padding: spacing.medium,
    borderRadius: 14,
    backgroundColor: colors.primarySurface,
  },
  noResultTitle: { color: "#0759A8", fontSize: 15, fontWeight: typography.extraBold },
  noResultText: { color: "#2563A8", fontSize: 13, marginTop: spacing.extraSmall },
  resultCard: {
    minHeight: 78,
    borderRadius: 16,
    backgroundColor: colors.surfaceMuted,
    flexDirection: "row",
    alignItems: "center",
    padding: 12,
    marginTop: spacing.large,
  },
  resultInfo: { flex: 1, marginLeft: spacing.small },
  resultName: { color: colors.textStrong, fontSize: 16, fontWeight: typography.extraBold },
  resultUsername: { color: colors.textMuted, fontSize: 13, marginTop: spacing.extraSmall },
  resultAction: {
    color: colors.primary,
    fontSize: 14,
    fontWeight: typography.extraBold,
    paddingHorizontal: spacing.extraSmall,
  },
  findButton: {
    height: 52,
    borderRadius: radii.medium,
    backgroundColor: colors.primary,
    alignItems: "center",
    justifyContent: "center",
    marginTop: spacing.small,
  },
  disabledButton: { backgroundColor: "#CBD5E1" },
  findButtonText: {
    color: colors.white,
    fontSize: typography.body,
    fontWeight: typography.extraBold,
  },
  searchRow: {
    height: 56,
    borderRadius: radii.medium,
    borderWidth: 1,
    borderColor: colors.borderInput,
    backgroundColor: colors.surface,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: spacing.medium,
    marginTop: spacing.large,
  },
});
